const lectureData = [
  {
    sn: 1,
    class: "IX",
    subject: "Physics",
    chapter_name: "Motion",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/0u0keGw9Nvk",
  },
  {
    sn: 2,
    class: "IX",
    subject: "Physics",
    chapter_name: "Motion",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/oF1IJLdHHdU",
  },
  {
    sn: 3,
    class: "IX",
    subject: "Physics",
    chapter_name: "Motion",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/EHw59xLqYaA",
  },
  {
    sn: 4,
    class: "IX",
    subject: "Physics",
    chapter_name: "Motion",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/g1yTbNBGUuc",
  },
  {
    sn: 5,
    class: "IX",
    subject: "Physics",
    chapter_name: "Motion",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/urobOjM_HeA",
  },
  {
    sn: 6,
    class: "IX",
    subject: "Physics",
    chapter_name: "Motion",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/tL9S76s6z1E",
  },
  {
    sn: 7,
    class: "IX",
    subject: "Physics",
    chapter_name: "Motion",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/Cgjj3fZ7_bQ",
  },
  {
    sn: 8,
    class: "IX",
    subject: "Physics",
    chapter_name: "Motion",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/4ZuImNqkxUg",
  },
  {
    sn: 9,
    class: "IX",
    subject: "Physics",
    chapter_name: "Motion",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/nU5WvpKV6MU",
  },
  {
    sn: 10,
    class: "IX",
    subject: "Physics",
    chapter_name: "Force and Laws of Motion",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/1VIN6SVyMfg",
  },
  {
    sn: 11,
    class: "IX",
    subject: "Physics",
    chapter_name: "Force and Laws of Motion",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/1M-fPTKft8o",
  },
  {
    sn: 12,
    class: "IX",
    subject: "Physics",
    chapter_name: "Force and Laws of Motion",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/J2kOHfm0o2U",
  },
  {
    sn: 13,
    class: "IX",
    subject: "Physics",
    chapter_name: "Force and Laws of Motion",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/jrSlx56dteI",
  },
  {
    sn: 14,
    class: "IX",
    subject: "Physics",
    chapter_name: "Force and Laws of Motion",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/3lEIQrDzDOk",
  },
  {
    sn: 15,
    class: "IX",
    subject: "Physics",
    chapter_name: "Force and Laws of Motion",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/IfIoaRwMASc",
  },
  {
    sn: 16,
    class: "IX",
    subject: "Physics",
    chapter_name: "Gravitation",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/Pe59zTwov_0",
  },
  {
    sn: 17,
    class: "IX",
    subject: "Physics",
    chapter_name: "Gravitation",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/1UNuIqlNy1M",
  },
  {
    sn: 18,
    class: "IX",
    subject: "Physics",
    chapter_name: "Gravitation",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/mA6L9obrfeI",
  },
  {
    sn: 19,
    class: "IX",
    subject: "Physics",
    chapter_name: "Gravitation",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/xGXk-llsJ6I",
  },
  {
    sn: 20,
    class: "IX",
    subject: "Physics",
    chapter_name: "Gravitation",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/IjHUjjEqQp8",
  },
  {
    sn: 21,
    class: "IX",
    subject: "Physics",
    chapter_name: "Gravitation",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/DnWYDba0rvc",
  },
  {
    sn: 22,
    class: "IX",
    subject: "Physics",
    chapter_name: "Gravitation",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/RBv3AZzjmJg",
  },
  {
    sn: 23,
    class: "IX",
    subject: "Physics",
    chapter_name: "Gravitation",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/Ryv-wn0Gs-8",
  },
  {
    sn: 24,
    class: "IX",
    subject: "Physics",
    chapter_name: "Gravitation",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/L0ErbFkh-6g",
  },
  {
    sn: 25,
    class: "IX",
    subject: "Physics",
    chapter_name: "Work and Energy",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/HkPpFcqHQ4Y",
  },
  {
    sn: 26,
    class: "IX",
    subject: "Physics",
    chapter_name: "Work and Energy",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/-kkJKSO94uE",
  },
  {
    sn: 27,
    class: "IX",
    subject: "Physics",
    chapter_name: "Work and Energy",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/GSj0TEKk8bE",
  },
  {
    sn: 28,
    class: "IX",
    subject: "Physics",
    chapter_name: "Work and Energy",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/rX51IaRCUOw",
  },
  {
    sn: 29,
    class: "IX",
    subject: "Physics",
    chapter_name: "Work and Energy",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/UzgamTe-StA",
  },
  {
    sn: 30,
    class: "IX",
    subject: "Physics",
    chapter_name: "Work and Energy",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/BoBg3I9cacY",
  },
  {
    sn: 31,
    class: "IX",
    subject: "Physics",
    chapter_name: "Work and Energy",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/48JoDjKvW1s",
  },
  {
    sn: 32,
    class: "IX",
    subject: "Physics",
    chapter_name: "Work and Energy",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/lIho1G0mYt0",
  },
  {
    sn: 33,
    class: "IX",
    subject: "Physics",
    chapter_name: "Sound",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/oISUS24nDnc",
  },
  {
    sn: 34,
    class: "IX",
    subject: "Physics",
    chapter_name: "Sound",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/t-6OZ7VHO4A",
  },
  {
    sn: 35,
    class: "IX",
    subject: "Physics",
    chapter_name: "Sound",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/XP2zo5AN0ao",
  },
  {
    sn: 36,
    class: "IX",
    subject: "Physics",
    chapter_name: "Sound",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/qV-ajSja7Gc",
  },
  {
    sn: 37,
    class: "IX",
    subject: "Physics",
    chapter_name: "Sound",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/oXdD3_RoqBY",
  },
  {
    sn: 38,
    class: "IX",
    subject: "Physics",
    chapter_name: "Sound",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/BIHIOiLj9lc",
  },
  {
    sn: 39,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Matter in Our Surroundings",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/N5m5LEwEbo8",
  },
  {
    sn: 40,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Matter in Our Surroundings",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/cCP8DBPaxkI",
  },
  {
    sn: 41,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Matter in Our Surroundings",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/3jxhLBtIaJM",
  },
  {
    sn: 42,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Matter in Our Surroundings",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/Aw8JMSbeiE0",
  },
  {
    sn: 43,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Matter in Our Surroundings",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/0y5DDwqkJS8",
  },
  {
    sn: 44,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Matter in Our Surroundings",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/CkL4cX5iit8",
  },
  {
    sn: 45,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Is Matter Around Us Pure?",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/QJEAbWBJYV4",
  },
  {
    sn: 46,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Is Matter Around Us Pure?",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/q8-dK1U6Q6o",
  },
  {
    sn: 47,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Is Matter Around Us Pure?",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/Uga61Q0DDXk",
  },
  {
    sn: 48,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Is Matter Around Us Pure?",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/ZaYvhsDwnVY",
  },
  {
    sn: 49,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Is Matter Around Us Pure?",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/jrJm5rm0j0E",
  },
  {
    sn: 50,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Is Matter Around Us Pure?",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/kOF7qVNiUDk",
  },
  {
    sn: 51,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Is Matter Around Us Pure?",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/L1j73_FQOnc",
  },
  {
    sn: 52,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Atoms and Molecules",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/HLLIofb_gS8",
  },
  {
    sn: 53,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Atoms and Molecules",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/FGqoA1hGjQM",
  },
  {
    sn: 54,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Atoms and Molecules",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/-RSWN9VNj4I",
  },
  {
    sn: 55,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Atoms and Molecules",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/DINpO8OhXto",
  },
  {
    sn: 56,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Atoms and Molecules",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/6wcxIT9V3pM",
  },
  {
    sn: 57,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Atoms and Molecules",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/lPyzBtCOtyo",
  },
  {
    sn: 58,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Atoms and Molecules",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/BtVzGMfxa-c",
  },
  {
    sn: 59,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Atoms and Molecules",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/qAMdtBTzcBY",
  },
  {
    sn: 60,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Structure of the Atom",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/GAMqODKPGPA",
  },
  {
    sn: 61,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Structure of the Atom",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/H4M1SKJodHc",
  },
  {
    sn: 62,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Structure of the Atom",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/-cyR5h96LTw",
  },
  {
    sn: 63,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Structure of the Atom",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/BxsnWpqI1ro",
  },
  {
    sn: 64,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Structure of the Atom",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/ZS21KmpPhd4",
  },
  {
    sn: 65,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Structure of the Atom",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/5gtamI2_ek8",
  },
  {
    sn: 66,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Structure of the Atom",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/JLXM5XGByLU",
  },
  {
    sn: 67,
    class: "IX",
    subject: "Chemistry",
    chapter_name: "Structure of the Atom",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/NvsM_B0UPBE",
  },
  {
    sn: 68,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/NCDidMqrZYg",
  },
  {
    sn: 69,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/rLK-JUuV0_8",
  },
  {
    sn: 70,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/wspiXHLUHgg",
  },
  {
    sn: 71,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/1-u-Z2O381A",
  },
  {
    sn: 72,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/AnV_g7PRL5c",
  },
  {
    sn: 73,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/NydCiWsru_I",
  },
  {
    sn: 74,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/bOuUpIi27TQ",
  },
  {
    sn: 75,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/Aq_p8l9dj-8",
  },
  {
    sn: 76,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/TvmuJ52DUA0",
  },
  {
    sn: 77,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 10,
    video_link: "https://youtube.com/embed/TXObtmIM3gw",
  },
  {
    sn: 78,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Number System",
    lecture_number: 11,
    video_link: "https://youtube.com/embed/iD0gr590RIk",
  },
  {
    sn: 79,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/IF64RzmP_qU",
  },
  {
    sn: 80,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/wF6NTZrmYCw",
  },
  {
    sn: 81,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/77rCcvvZu_8",
  },
  {
    sn: 82,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/1Pin4PcRsHU",
  },
  {
    sn: 83,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/6f-UoIWd5rM",
  },
  {
    sn: 84,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/iv1ma3VCylI",
  },
  {
    sn: 85,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/m5ywiPGqMUU",
  },
  {
    sn: 86,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Linear Equation in two variable",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/uMEwW6hsxNw",
  },
  {
    sn: 87,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Linear Equation in two variable",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/9qNuet8hPSU",
  },
  {
    sn: 88,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Coordinate Geometry",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/vmre7qJDI6Y",
  },
  {
    sn: 89,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Introduction to Euclid Geometry",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/1F_rYdGRVX0",
  },
  {
    sn: 90,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Introduction to Euclid Geometry",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/h_1uiUU2iuY",
  },
  {
    sn: 91,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Lines & Angle",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/agZrVYDcsH4",
  },
  {
    sn: 92,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Lines & Angle",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/aK93Xuy5Q_o",
  },
  {
    sn: 93,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Lines & Angle",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/SeyyNN90JXY",
  },
  {
    sn: 94,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Lines & Angle",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/BuDsMOhCfi8",
  },
  {
    sn: 95,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Lines & Angle",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/BXL8vzitziI",
  },
  {
    sn: 96,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/nBQF8BN6m0c",
  },
  {
    sn: 97,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/xjngh7bXcWE",
  },
  {
    sn: 98,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/L1Ez6rS9t_s",
  },
  {
    sn: 99,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/fNRpaT40HEI",
  },
  {
    sn: 100,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/cKOecC9imfM",
  },
  {
    sn: 101,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/fJGPX3jMvbg",
  },
  {
    sn: 102,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/zJMmBmudk2g",
  },
  {
    sn: 103,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Quadrilateral",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/ZwuQXSaNOTs",
  },
  {
    sn: 104,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Quadrilateral",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/JioHFo-yHpA",
  },
  {
    sn: 105,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Quadrilateral",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/Inu9EP9jiNk",
  },
  {
    sn: 106,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Quadrilateral",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/2imnS3ejFrg",
  },
  {
    sn: 107,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Quadrilateral",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/7zRz7_JEOvU",
  },
  {
    sn: 108,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Areas of parallelogram and Triangle",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/anTY8tWnfjQ",
  },
  {
    sn: 109,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Areas of parallelogram and Triangle",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/3guqfQeFjlw",
  },
  {
    sn: 110,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Areas of parallelogram and Triangle",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/FncBtP5pxi4",
  },
  {
    sn: 111,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Areas of parallelogram and Triangle",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/x0NQgO8t6oE",
  },
  {
    sn: 112,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Circles",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/B4-2u7Wb84g",
  },
  {
    sn: 113,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Circles",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/IT9S67KspYk",
  },
  {
    sn: 114,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Circles",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/SgR-ur95A1U",
  },
  {
    sn: 115,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Circles",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/lfE0G6Gmyyk",
  },
  {
    sn: 116,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Circles",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/qMRZMmYcDr4",
  },
  {
    sn: 117,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Constructions",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/Fzxlh0GqVpM",
  },
  {
    sn: 118,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Constructions",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/tURM8cmP29M",
  },
  {
    sn: 119,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Heron's Formula",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/rhbge1a1hpQ",
  },
  {
    sn: 120,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Heron's Formula",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/gn8_Nly_Gyo",
  },
  {
    sn: 121,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Statistics",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/CpvaG1I4leQ",
  },
  {
    sn: 122,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Statistics",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/6lBZ3GQYNbY",
  },
  {
    sn: 123,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Statistics",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/x5MI6U0JJco",
  },
  {
    sn: 124,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Statistics",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/DPbyXQ36RR0",
  },
  {
    sn: 125,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Probability",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/rJ61WUmD1CQ",
  },
  {
    sn: 126,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Probability",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/3OxN4rWATSk",
  },
  {
    sn: 127,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/Qt0RycOwB-o",
  },
  {
    sn: 128,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/hCVsIqpmtZY",
  },
  {
    sn: 129,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/q1EyHPJggHo",
  },
  {
    sn: 130,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/GFLPGau8Iec",
  },
  {
    sn: 131,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/piTDZz6nt4Y",
  },
  {
    sn: 132,
    class: "IX",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/dHvwp6DNOLs",
  },
  {
    sn: 133,
    class: "IX",
    subject: "Biology",
    chapter_name: "The Fundamental unit of life",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/L78ZdfaQn5U",
  },
  {
    sn: 134,
    class: "IX",
    subject: "Biology",
    chapter_name: "The Fundamental unit of life",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/gQ46RG-yUQM",
  },
  {
    sn: 135,
    class: "IX",
    subject: "Biology",
    chapter_name: "The Fundamental unit of life",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/zjZUQIStDR0",
  },
  {
    sn: 136,
    class: "IX",
    subject: "Biology",
    chapter_name: "The Fundamental unit of life",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/kOgMTabXYmE",
  },
  {
    sn: 137,
    class: "IX",
    subject: "Biology",
    chapter_name: "The Fundamental unit of life",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/pKTGL3_V5Ko",
  },
  {
    sn: 138,
    class: "IX",
    subject: "Biology",
    chapter_name: "The Fundamental unit of life",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/0Z79Z7rfvsY",
  },
  {
    sn: 139,
    class: "IX",
    subject: "Biology",
    chapter_name: "The Fundamental unit of life",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/MwueRpSoLnI",
  },
  {
    sn: 140,
    class: "IX",
    subject: "Biology",
    chapter_name: "The Fundamental unit of life",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/f0iNhcd9HBM",
  },
  {
    sn: 141,
    class: "IX",
    subject: "Biology",
    chapter_name: "The Fundamental unit of life",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/1NYz94iRRGA",
  },
  {
    sn: 142,
    class: "IX",
    subject: "Biology",
    chapter_name: "The Fundamental unit of life",
    lecture_number: 10,
    video_link: "https://youtube.com/embed/DFaSCPMfcAE",
  },
  {
    sn: 143,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/K2WVP4Z7y9M",
  },
  {
    sn: 144,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/Gb55XsU8tOY",
  },
  {
    sn: 145,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/ogE4_i02CVc",
  },
  {
    sn: 146,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/3Mah8Y21OvM",
  },
  {
    sn: 147,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/Fa4Wm5neJhU",
  },
  {
    sn: 148,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/PLt0k28xrBI",
  },
  {
    sn: 149,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/iPkbRVT-3PE",
  },
  {
    sn: 150,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/U3fSQd3HPPU",
  },
  {
    sn: 151,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/g2Y2yfaZE1Y",
  },
  {
    sn: 152,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 10,
    video_link: "https://youtube.com/embed/RRTa9wwKIp8",
  },
  {
    sn: 153,
    class: "IX",
    subject: "Biology",
    chapter_name: "Tissues",
    lecture_number: 11,
    video_link: "https://youtube.com/embed/uc2sJnXJR_4",
  },
  {
    sn: 154,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/rZmHNEl5b-E",
  },
  {
    sn: 155,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/N4UToFvLldc",
  },
  {
    sn: 156,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/PLgpSQZ8BgA",
  },
  {
    sn: 157,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/fyxp8mbh0bE",
  },
  {
    sn: 158,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/XISVUFZD6Sc",
  },
  {
    sn: 159,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/2xnlZtX4vLc",
  },
  {
    sn: 160,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/c6cWAZ8HvN0",
  },
  {
    sn: 161,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/YS-jxQ7WR-4",
  },
  {
    sn: 162,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/sIjP6XETdkU",
  },
  {
    sn: 163,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 10,
    video_link: "https://youtube.com/embed/6xo_55f8BO0",
  },
  {
    sn: 164,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 11,
    video_link: "https://youtube.com/embed/gSXTbJMJfwA",
  },
  {
    sn: 165,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 12,
    video_link: "https://youtube.com/embed/J4LctqrX6z8",
  },
  {
    sn: 166,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 13,
    video_link: "https://youtube.com/embed/V5sogmQTGY8",
  },
  {
    sn: 167,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 14,
    video_link: "https://youtube.com/embed/7ck2ohevPp4",
  },
  {
    sn: 168,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 15,
    video_link: "https://youtube.com/embed/RBNCGRP1gOM",
  },
  {
    sn: 169,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 16,
    video_link: "https://youtube.com/embed/me-j5IzWL64",
  },
  {
    sn: 170,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 17,
    video_link: "https://youtube.com/embed/XILsBEpKhhU",
  },
  {
    sn: 171,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 18,
    video_link: "https://youtube.com/embed/vUXJzx-P8BI",
  },
  {
    sn: 172,
    class: "IX",
    subject: "Biology",
    chapter_name: "Diversity in Living Organisms",
    lecture_number: 19,
    video_link: "https://youtube.com/embed/Ow4ed83k7JM",
  },
  {
    sn: 173,
    class: "IX",
    subject: "Biology",
    chapter_name: "Why Do We Fall Ill?",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/UDPHnnzOxg8",
  },
  {
    sn: 174,
    class: "IX",
    subject: "Biology",
    chapter_name: "Why Do We Fall Ill?",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/GUzFnyDrsQU",
  },
  {
    sn: 175,
    class: "IX",
    subject: "Biology",
    chapter_name: "Why Do We Fall Ill?",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/m9gq1MYuP_0",
  },
  {
    sn: 176,
    class: "IX",
    subject: "Biology",
    chapter_name: "Why Do We Fall Ill?",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/sKYZA-y1acs",
  },
  {
    sn: 177,
    class: "IX",
    subject: "Biology",
    chapter_name: "Why Do We Fall Ill?",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/DK2Qm_94rbQ",
  },
  {
    sn: 178,
    class: "IX",
    subject: "Biology",
    chapter_name: "Why Do We Fall Ill?",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/QtrdNWBfFpA",
  },
  {
    sn: 179,
    class: "IX",
    subject: "Biology",
    chapter_name: "Natural Resources",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/x7xNC-3qJHA",
  },
  {
    sn: 180,
    class: "IX",
    subject: "Biology",
    chapter_name: "Natural Resources",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/6ZPUQk-9sf4",
  },
  {
    sn: 181,
    class: "IX",
    subject: "Biology",
    chapter_name: "Natural Resources",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/E2XTD4oH8MM",
  },
  {
    sn: 182,
    class: "IX",
    subject: "Biology",
    chapter_name: "Natural Resources",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/gV68_VQVWVU",
  },
  {
    sn: 183,
    class: "IX",
    subject: "Biology",
    chapter_name: "Natural Resources",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/TjCSsqNoV8M",
  },
  {
    sn: 184,
    class: "IX",
    subject: "Biology",
    chapter_name: "Natural Resources",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/mb7HkBUlz-U",
  },
  {
    sn: 185,
    class: "IX",
    subject: "Biology",
    chapter_name: "Natural Resources",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/xRRy8Y1ism0",
  },
  {
    sn: 186,
    class: "IX",
    subject: "Biology",
    chapter_name: "Improvement in Food Resources",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/CGj6DoppvnA",
  },
  {
    sn: 187,
    class: "IX",
    subject: "Biology",
    chapter_name: "Improvement in Food Resources",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/gldDqCSeDow",
  },
  {
    sn: 188,
    class: "IX",
    subject: "Biology",
    chapter_name: "Improvement in Food Resources",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/ms6LcNBhPsI",
  },
  {
    sn: 189,
    class: "IX",
    subject: "Biology",
    chapter_name: "Improvement in Food Resources",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/8TFzrli5Lhg",
  },
  {
    sn: 190,
    class: "IX",
    subject: "Biology",
    chapter_name: "Improvement in Food Resources",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/ierqXHxtB10",
  },
  {
    sn: 191,
    class: "IX",
    subject: "Biology",
    chapter_name: "Improvement in Food Resources",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/R8Z7CnLSLdc",
  },
  {
    sn: 192,
    class: "IX",
    subject: "Biology",
    chapter_name: "Improvement in Food Resources",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/ObjssK-Pxs8",
  },
  {
    sn: 193,
    class: "IX",
    subject: "Biology",
    chapter_name: "Improvement in Food Resources",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/iOG0Z26d8ao",
  },
  {
    sn: 194,
    class: "IX",
    subject: "Biology",
    chapter_name: "Improvement in Food Resources",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/a5s_zPv0xYU",
  },
  {
    sn: 195,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/hpRGxDyQpiE",
  },
  {
    sn: 196,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/jGncR7ytaeo",
  },
  {
    sn: 197,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/6tuEjcY_be0",
  },
  {
    sn: 198,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/LMRumXsytIw",
  },
  {
    sn: 199,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/P_0v6KJl8bs",
  },
  {
    sn: 200,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/PE37E78ZaPU",
  },
  {
    sn: 201,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/geK2824Tons",
  },
  {
    sn: 202,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/sHe5-Ats3Yw",
  },
  {
    sn: 203,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/3RGoYeLj2xk",
  },
  {
    sn: 204,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 10,
    video_link: "https://youtube.com/embed/VZojCpG9zU4",
  },
  {
    sn: 205,
    class: "X",
    subject: "Physics",
    chapter_name: "Light - Reflection and Refraction",
    lecture_number: 11,
    video_link: "https://youtube.com/embed/KoSKqQZ4UR4",
  },
  {
    sn: 206,
    class: "X",
    subject: "Physics",
    chapter_name: "Human Eye and Colourful World",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/IdB05ZXE_Gk",
  },
  {
    sn: 207,
    class: "X",
    subject: "Physics",
    chapter_name: "Human Eye and Colourful World",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/Q-PEmcZXhEw",
  },
  {
    sn: 208,
    class: "X",
    subject: "Physics",
    chapter_name: "Human Eye and Colourful World",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/o1cxV3lNcvM",
  },
  {
    sn: 209,
    class: "X",
    subject: "Physics",
    chapter_name: "Human Eye and Colourful World",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/n6S_rTRIxS4",
  },
  {
    sn: 210,
    class: "X",
    subject: "Physics",
    chapter_name: "Human Eye and Colourful World",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/P9gvbJaJJjA",
  },
  {
    sn: 211,
    class: "X",
    subject: "Physics",
    chapter_name: "Human Eye and Colourful World",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/NpdKiYJCjdA",
  },
  {
    sn: 212,
    class: "X",
    subject: "Physics",
    chapter_name: "Human Eye and Colourful World",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/3Vv4X6IiJHs",
  },
  {
    sn: 213,
    class: "X",
    subject: "Physics",
    chapter_name: "Human Eye and Colourful World",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/Mxm4eoyk_rI",
  },
  {
    sn: 214,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/NP3YUu7T3IY",
  },
  {
    sn: 215,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/HOmewsD9zIU",
  },
  {
    sn: 216,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/YACICckVYdM",
  },
  {
    sn: 217,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/VNKo3hwiQk0",
  },
  {
    sn: 218,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/uCrKlf8F9ZY",
  },
  {
    sn: 219,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/D7DCjI-PG64",
  },
  {
    sn: 220,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/UWQU9QojhAA",
  },
  {
    sn: 221,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/zT52HMxbGNk",
  },
  {
    sn: 222,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/0YXooLhYRb8",
  },
  {
    sn: 223,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 10,
    video_link: "https://youtube.com/embed/jQf8_fMq4rU",
  },
  {
    sn: 224,
    class: "X",
    subject: "Physics",
    chapter_name: "Electricity",
    lecture_number: 11,
    video_link: "https://youtube.com/embed/yAoIQ6Ayrvc",
  },
  {
    sn: 225,
    class: "X",
    subject: "Physics",
    chapter_name: "Magnetic Effects of Electric Current",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/-d6p-hPCSjA",
  },
  {
    sn: 226,
    class: "X",
    subject: "Physics",
    chapter_name: "Magnetic Effects of Electric Current",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/NnEXdZHOcRU",
  },
  {
    sn: 227,
    class: "X",
    subject: "Physics",
    chapter_name: "Magnetic Effects of Electric Current",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/k5Fg8DwFZaU",
  },
  {
    sn: 228,
    class: "X",
    subject: "Physics",
    chapter_name: "Magnetic Effects of Electric Current",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/YBjDvHJcGf8",
  },
  {
    sn: 229,
    class: "X",
    subject: "Physics",
    chapter_name: "Magnetic Effects of Electric Current",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/xXWXvJBv6Ms",
  },
  {
    sn: 230,
    class: "X",
    subject: "Physics",
    chapter_name: "Magnetic Effects of Electric Current",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/wSAzWwNcG0M",
  },
  {
    sn: 231,
    class: "X",
    subject: "Physics",
    chapter_name: "Magnetic Effects of Electric Current",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/EGcXMUj7VTg",
  },
  {
    sn: 232,
    class: "X",
    subject: "Physics",
    chapter_name: "Magnetic Effects of Electric Current",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/wc9bzduAgSU",
  },
  {
    sn: 233,
    class: "X",
    subject: "Physics",
    chapter_name: "Sources of Energy",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/pMhq4z1GocI",
  },
  {
    sn: 234,
    class: "X",
    subject: "Physics",
    chapter_name: "Sources of Energy",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/bQqbzWy7kPo",
  },
  {
    sn: 235,
    class: "X",
    subject: "Physics",
    chapter_name: "Sources of Energy",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/oCtRMbroavk",
  },
  {
    sn: 236,
    class: "X",
    subject: "Physics",
    chapter_name: "Sources of Energy",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/CQt7SB1MqcM",
  },
  {
    sn: 237,
    class: "X",
    subject: "Physics",
    chapter_name: "Sources of Energy",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/sMHdsq6Fz-U",
  },
  {
    sn: 238,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Chemical Reactions and Equations",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/IQzw5r4H1pA",
  },
  {
    sn: 239,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Chemical Reactions and Equations",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/zCjw3tarK9o",
  },
  {
    sn: 240,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Chemical Reactions and Equations",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/zZzJZTNcG8E",
  },
  {
    sn: 241,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Chemical Reactions and Equations",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/T1J2-WQLwRQ",
  },
  {
    sn: 242,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Chemical Reactions and Equations",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/sjN9cQng5jQ",
  },
  {
    sn: 243,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Chemical Reactions and Equations",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/EeVumV3w_Do",
  },
  {
    sn: 244,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Chemical Reactions and Equations",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/g5SBp7K89Wk",
  },
  {
    sn: 245,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Chemical Reactions and Equations",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/LDzVmD9M_lE",
  },
  {
    sn: 246,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Acids, bases and salts",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/6CBZFQRbx4w",
  },
  {
    sn: 247,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Acids, bases and salts",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/jy94ASlKRC0",
  },
  {
    sn: 248,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Acids, bases and salts",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/HlbW5hQ2h1w",
  },
  {
    sn: 249,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Acids, bases and salts",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/H59KiCr503M",
  },
  {
    sn: 250,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Acids, bases and salts",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/27jRMUyltiw",
  },
  {
    sn: 251,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Acids, bases and salts",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/ilXQYudWB04",
  },
  {
    sn: 252,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Acids, bases and salts",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/RqnioPGKeZQ",
  },
  {
    sn: 253,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Acids, bases and salts",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/FGxFExz0Q_M",
  },
  {
    sn: 254,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Acids, bases and salts",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/wwO7tuGWbR8",
  },
  {
    sn: 255,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Acids, bases and salts",
    lecture_number: 10,
    video_link: "https://youtube.com/embed/upQMbUvdE0g",
  },
  {
    sn: 256,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Metals and Non-Metals",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/euZVypINNjo",
  },
  {
    sn: 257,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Metals and Non-Metals",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/UJBQQ1XbY08",
  },
  {
    sn: 258,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Metals and Non-Metals",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/SKWvYwZQc9E",
  },
  {
    sn: 259,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Metals and Non-Metals",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/zdzm48ytQCQ",
  },
  {
    sn: 260,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Metals and Non-Metals",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/T07q_v2mMfc",
  },
  {
    sn: 261,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Metals and Non-Metals",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/qyxo-x5Lxx0",
  },
  {
    sn: 262,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Metals and Non-Metals",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/zTpSTwx_cwM",
  },
  {
    sn: 263,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Metals and Non-Metals",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/fJG86mxCNH4",
  },
  {
    sn: 264,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Carbon and it's Compounds",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/Z751hJk3ifo",
  },
  {
    sn: 265,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Carbon and it's Compounds",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/DyulfbupSXI",
  },
  {
    sn: 266,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Carbon and it's Compounds",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/-dIFhM7o6So",
  },
  {
    sn: 267,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Carbon and it's Compounds",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/l841T9KkB8Y",
  },
  {
    sn: 268,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Carbon and it's Compounds",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/yQFA-JwLP5A",
  },
  {
    sn: 269,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Carbon and it's Compounds",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/0x0s78SvXTQ",
  },
  {
    sn: 270,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Carbon and it's Compounds",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/qci3ODe_fLY",
  },
  {
    sn: 271,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Carbon and it's Compounds",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/AtXp6KQGfNo",
  },
  {
    sn: 272,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Carbon and it's Compounds",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/flnpQnpNSkQ",
  },
  {
    sn: 273,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Carbon and it's Compounds",
    lecture_number: 10,
    video_link: "https://youtube.com/embed/gsVQNnnDU3g",
  },
  {
    sn: 274,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Periodic classification of Elements",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/WsJuCgxCji0",
  },
  {
    sn: 275,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Periodic classification of Elements",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/UuW0oKG4h1w",
  },
  {
    sn: 276,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Periodic classification of Elements",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/RXIlC3i6oKk",
  },
  {
    sn: 277,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Periodic classification of Elements",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/wkfE7ytkBkc",
  },
  {
    sn: 278,
    class: "X",
    subject: "Chemistry",
    chapter_name: "Periodic classification of Elements",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/kW-F3BtitlQ",
  },
  {
    sn: 279,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Real Numbers",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/EstB5T4V8Ls",
  },
  {
    sn: 280,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Real Numbers",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/c7vtGzKHfPw",
  },
  {
    sn: 281,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Real Numbers",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/RrupzC1aXCM",
  },
  {
    sn: 282,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Real Numbers",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/RKDI29aFv34",
  },
  {
    sn: 283,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Real Numbers",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/7hnWAoldJrw",
  },
  {
    sn: 284,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Real Numbers",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/Xxjwonfgkas",
  },
  {
    sn: 285,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/nS67F3xroXc",
  },
  {
    sn: 286,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/35Yt3CqgU9U",
  },
  {
    sn: 287,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/zPLRZsu38qA",
  },
  {
    sn: 288,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/9yOpS2ty2kI",
  },
  {
    sn: 289,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/jLLULnonIX8",
  },
  {
    sn: 290,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Polynomials",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/5EpIpFsgabc",
  },
  {
    sn: 291,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Pair of Linear equation in two variable",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/JHXoNs_AC5Q",
  },
  {
    sn: 292,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Pair of Linear equation in two variable",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/mqZ15wD36zs",
  },
  {
    sn: 293,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Pair of Linear equation in two variable",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/4ddoT_UiYiI",
  },
  {
    sn: 294,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Pair of Linear equation in two variable",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/n0J6BMfGGEI",
  },
  {
    sn: 295,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Pair of Linear equation in two variable",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/NLhJYE1eFn4",
  },
  {
    sn: 296,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Pair of Linear equation in two variable",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/XpEJIT-QsMA",
  },
  {
    sn: 297,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Quadratic Equation",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/EYDeVjztbjI",
  },
  {
    sn: 298,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Quadratic Equation",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/Ea43xhoyNWs",
  },
  {
    sn: 299,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Quadratic Equation",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/6tobHXvdgrw",
  },
  {
    sn: 300,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Quadratic Equation",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/Yd79v3Y1I0U",
  },
  {
    sn: 301,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Quadratic Equation",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/EDJHvF5yBS0",
  },
  {
    sn: 302,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Quadratic Equation",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/ZX3ifzbgO1E",
  },
  {
    sn: 303,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Arithmetic Progressions",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/8u4NgB0Pyvg",
  },
  {
    sn: 304,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Arithmetic Progressions",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/DmQTooveMjQ",
  },
  {
    sn: 305,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Arithmetic Progressions",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/RLBGAu9x7FA",
  },
  {
    sn: 306,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Arithmetic Progressions",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/Onvme95RD9U",
  },
  {
    sn: 307,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Coordinate Geometry",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/LrBnpjUWJ20",
  },
  {
    sn: 308,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Coordinate Geometry",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/VhkkZdWDzHw",
  },
  {
    sn: 309,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Coordinate Geometry",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/dCjrL88ByMk",
  },
  {
    sn: 310,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Coordinate Geometry",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/sXKJjWA6ocw",
  },
  {
    sn: 311,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Coordinate Geometry",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/XYXysliRC7c",
  },
  {
    sn: 312,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/O9J9MWcJG18",
  },
  {
    sn: 313,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/52K0b6Z2lok",
  },
  {
    sn: 314,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/2EWALCcg3fE",
  },
  {
    sn: 315,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/r0jbwH9hFw0",
  },
  {
    sn: 316,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/rWYXUpaa2uo",
  },
  {
    sn: 317,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Triangles",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/bpDvHsL4rzE",
  },
  {
    sn: 318,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Introduction to Trigonometry",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/2Hd_kgwMhy8",
  },
  {
    sn: 319,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Introduction to Trigonometry",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/DjWu2CLtD4w",
  },
  {
    sn: 320,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Introduction to Trigonometry",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/fQ27MlzQmjk",
  },
  {
    sn: 321,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Introduction to Trigonometry",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/eadgb4uDSLY",
  },
  {
    sn: 322,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Some Applications of Trigonometry",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/j4OiblLZoF4",
  },
  {
    sn: 323,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Some Applications of Trigonometry",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/HH-JH7k8zd8",
  },
  {
    sn: 324,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Circles",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/3vxUV11tLGI",
  },
  {
    sn: 325,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Circles",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/jlo1JdWhznA",
  },
  {
    sn: 326,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Circles",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/38aLZDkmUvU",
  },
  {
    sn: 327,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Constructions",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/3xeqNrbT3ak",
  },
  {
    sn: 328,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Areas Related to Circles",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/QYWTZKUCqv4",
  },
  {
    sn: 329,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Areas Related to Circles",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/bE1NgE5l5LA",
  },
  {
    sn: 330,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Statistics",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/CGYeawrEW0c",
  },
  {
    sn: 331,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Statistics",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/LahMscT5C5s",
  },
  {
    sn: 332,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Statistics",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/mIj7ZcRWkSE",
  },
  {
    sn: 333,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Statistics",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/wDJn6Vnocus",
  },
  {
    sn: 334,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Statistics",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/b6IaYlW4kJc",
  },
  {
    sn: 335,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/Qt0RycOwB-o",
  },
  {
    sn: 336,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/hCVsIqpmtZY",
  },
  {
    sn: 337,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/q1EyHPJggHo",
  },
  {
    sn: 338,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/GFLPGau8Iec",
  },
  {
    sn: 339,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/piTDZz6nt4Y",
  },
  {
    sn: 340,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Surface Areas and Volumes",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/dHvwp6DNOLs",
  },
  {
    sn: 341,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Probability",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/rJ61WUmD1CQ",
  },
  {
    sn: 342,
    class: "X",
    subject: "Mathematics",
    chapter_name: "Probability",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/3OxN4rWATSk",
  },
  {
    sn: 343,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/BVqyHC4coiM",
  },
  {
    sn: 344,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/3ob9MpyHlpE",
  },
  {
    sn: 345,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/IRcDpHHguXM",
  },
  {
    sn: 346,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/V-kmZVE85wA",
  },
  {
    sn: 347,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/xYwNdpsWCkA",
  },
  {
    sn: 348,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/hdZT_XZ3aqo",
  },
  {
    sn: 349,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/bLBPt5rxFBE",
  },
  {
    sn: 350,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/REqy8mWMn6E",
  },
  {
    sn: 351,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/zRuBuyXSz-o",
  },
  {
    sn: 352,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 10,
    video_link: "https://youtube.com/embed/9JolpJ0mR3Q",
  },
  {
    sn: 353,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 11,
    video_link: "https://youtube.com/embed/hd-LJKhC134",
  },
  {
    sn: 354,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 12,
    video_link: "https://youtube.com/embed/6tazE-Oi9U8",
  },
  {
    sn: 355,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 13,
    video_link: "https://youtube.com/embed/wvZdtfs0QE4",
  },
  {
    sn: 356,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 14,
    video_link: "https://youtube.com/embed/Lc4ZwWkFIYU",
  },
  {
    sn: 357,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 15,
    video_link: "https://youtube.com/embed/ow-Q8zzpRXI",
  },
  {
    sn: 358,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 16,
    video_link: "https://youtube.com/embed/IAndi3yFCS4",
  },
  {
    sn: 359,
    class: "X",
    subject: "Biology",
    chapter_name: "Life Processes",
    lecture_number: 17,
    video_link: "https://youtube.com/embed/itQ0IUIbLK0",
  },
  {
    sn: 360,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/I8_jCcMOgJ8",
  },
  {
    sn: 361,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/GHiCGMq5oA8",
  },
  {
    sn: 362,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/darM5xt8DvY",
  },
  {
    sn: 363,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/3fckU9CoBac",
  },
  {
    sn: 364,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/5GuT9UErO90",
  },
  {
    sn: 365,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/IEfwuARk8e8",
  },
  {
    sn: 366,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/m-hdFOnX1Uc",
  },
  {
    sn: 367,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 8,
    video_link: "https://youtube.com/embed/-bnnxIJj6WU",
  },
  {
    sn: 368,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 9,
    video_link: "https://youtube.com/embed/iiNn2vPrisw",
  },
  {
    sn: 369,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 10,
    video_link: "https://youtube.com/embed/Z8pSEVLR5YM",
  },
  {
    sn: 370,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 11,
    video_link: "https://youtube.com/embed/RA5n7TDzVOE",
  },
  {
    sn: 371,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 12,
    video_link: "https://youtube.com/embed/kemmLzETrrg",
  },
  {
    sn: 372,
    class: "X",
    subject: "Biology",
    chapter_name: "Control and Coordination",
    lecture_number: 13,
    video_link: "https://youtube.com/embed/iirhx4cTKaU",
  },
  {
    sn: 373,
    class: "X",
    subject: "Biology",
    chapter_name: "How do Organism Reproduce?",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/EjLS3luPsm0",
  },
  {
    sn: 374,
    class: "X",
    subject: "Biology",
    chapter_name: "How do Organism Reproduce?",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/pEwAJCkHg7M",
  },
  {
    sn: 375,
    class: "X",
    subject: "Biology",
    chapter_name: "How do Organism Reproduce?",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/Ff-PHkX9oHo",
  },
  {
    sn: 376,
    class: "X",
    subject: "Biology",
    chapter_name: "How do Organism Reproduce?",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/eTjRWKX9Ajc",
  },
  {
    sn: 377,
    class: "X",
    subject: "Biology",
    chapter_name: "How do Organism Reproduce?",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/VjhV227nppI",
  },
  {
    sn: 378,
    class: "X",
    subject: "Biology",
    chapter_name: "How do Organism Reproduce?",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/mLhXgOF6hB0",
  },
  {
    sn: 379,
    class: "X",
    subject: "Biology",
    chapter_name: "How do Organism Reproduce?",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/3FEybwGfAgo",
  },
  {
    sn: 380,
    class: "X",
    subject: "Biology",
    chapter_name: "Heredity and Evolution",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/iChzDjAcNw8",
  },
  {
    sn: 381,
    class: "X",
    subject: "Biology",
    chapter_name: "Heredity and Evolution",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/ZmwN066StRI",
  },
  {
    sn: 382,
    class: "X",
    subject: "Biology",
    chapter_name: "Heredity and Evolution",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/HcmkEaZffjI",
  },
  {
    sn: 383,
    class: "X",
    subject: "Biology",
    chapter_name: "Heredity and Evolution",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/fdJxDdxOKoM",
  },
  {
    sn: 384,
    class: "X",
    subject: "Biology",
    chapter_name: "Heredity and Evolution",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/_6Txa7l8sqI",
  },
  {
    sn: 385,
    class: "X",
    subject: "Biology",
    chapter_name: "Heredity and Evolution",
    lecture_number: 6,
    video_link: "https://youtube.com/embed/fOS6cd7iveY",
  },
  {
    sn: 386,
    class: "X",
    subject: "Biology",
    chapter_name: "Heredity and Evolution",
    lecture_number: 7,
    video_link: "https://youtube.com/embed/4SEjT4yN2Z0",
  },
  {
    sn: 387,
    class: "X",
    subject: "Biology",
    chapter_name: "Our Environment",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/2EaFAlmvmFk",
  },
  {
    sn: 388,
    class: "X",
    subject: "Biology",
    chapter_name: "Our Environment",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/_6XReSgnbpU",
  },
  {
    sn: 389,
    class: "X",
    subject: "Biology",
    chapter_name: "Our Environment",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/gm4XPIJ3AEM",
  },
  {
    sn: 390,
    class: "X",
    subject: "Biology",
    chapter_name: "Our Environment",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/7qGRtBH99cQ",
  },
  {
    sn: 391,
    class: "X",
    subject: "Biology",
    chapter_name: "Our Environment",
    lecture_number: 5,
    video_link: "https://youtube.com/embed/7Av9Bs_riQ4",
  },
  {
    sn: 392,
    class: "X",
    subject: "Biology",
    chapter_name: "Management of Natural Resources",
    lecture_number: 1,
    video_link: "https://youtube.com/embed/oGX7SwMq-SA",
  },
  {
    sn: 393,
    class: "X",
    subject: "Biology",
    chapter_name: "Management of Natural Resources",
    lecture_number: 2,
    video_link: "https://youtube.com/embed/LFnVqk0iNzY",
  },
  {
    sn: 394,
    class: "X",
    subject: "Biology",
    chapter_name: "Management of Natural Resources",
    lecture_number: 3,
    video_link: "https://youtube.com/embed/HBulG6JRZt0",
  },
  {
    sn: 395,
    class: "X",
    subject: "Biology",
    chapter_name: "Management of Natural Resources",
    lecture_number: 4,
    video_link: "https://youtube.com/embed/IxLYCg1pgO0",
  },
];

module.exports = { data: lectureData };
